// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.sgo.rootest.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import org.sgo.rootest.client.managed.request.ApplicationEntityTypesProcessor;
import org.sgo.rootest.client.managed.request.ApplicationRequestFactory;
import org.sgo.rootest.client.managed.request.IssueProxy;
import org.sgo.rootest.client.managed.ui.IssueListView;
import org.sgo.rootest.client.managed.ui.IssueMobileListView;
import org.sgo.rootest.client.scaffold.ScaffoldApp;
import org.sgo.rootest.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleIssue(IssueProxy isNull) {
                setResult(new IssueListActivity(requests, ScaffoldApp.isMobile() ? IssueMobileListView.instance() : IssueListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
