// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.sgo.rootest.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import org.sgo.rootest.client.managed.activity.IssueEditActivityWrapper.View;
import org.sgo.rootest.client.managed.request.ApplicationRequestFactory;
import org.sgo.rootest.client.managed.request.IssueProxy;
import org.sgo.rootest.client.scaffold.activity.IsScaffoldMobileActivity;
import org.sgo.rootest.client.scaffold.place.ProxyEditView;
import org.sgo.rootest.client.scaffold.place.ProxyListPlace;
import org.sgo.rootest.client.scaffold.place.ProxyPlace;

public abstract class IssueEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends org.sgo.rootest.client.scaffold.place.ProxyEditView<org.sgo.rootest.client.managed.request.IssueProxy, V>> extends ProxyEditView<IssueProxy, V> {
    }
}
