// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.sgo.rootest.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("org.sgo.rootest.domain.Issue")
@ServiceName("org.sgo.rootest.domain.Issue")
public interface IssueRequest extends RequestContext {

    abstract InstanceRequest<org.sgo.rootest.client.managed.request.IssueProxy, java.lang.Void> persist();

    abstract InstanceRequest<org.sgo.rootest.client.managed.request.IssueProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countIssues();

    abstract Request<java.util.List<org.sgo.rootest.client.managed.request.IssueProxy>> findAllIssues();

    abstract Request<org.sgo.rootest.client.managed.request.IssueProxy> findIssue(Long id);

    abstract Request<java.util.List<org.sgo.rootest.client.managed.request.IssueProxy>> findIssueEntries(int firstResult, int maxResults);
}
