// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.sgo.rootest.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import org.sgo.rootest.client.managed.request.ApplicationEntityTypesProcessor;
import org.sgo.rootest.client.managed.request.IssueProxy;
import org.sgo.rootest.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleIssue(IssueProxy isNull) {
                setResult("Issues");
            }
        }.process(object.getProxyClass());
    }
}
