// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.sgo.rootest.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import org.sgo.rootest.client.managed.request.IssueProxy;
import org.sgo.rootest.client.scaffold.place.ProxyDetailsView;
import org.sgo.rootest.client.scaffold.place.ProxyListView;

public abstract class IssueDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<IssueProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement summary;

    IssueProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(IssueProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        summary.setInnerText(proxy.getSummary() == null ? "" : String.valueOf(proxy.getSummary()));
        displayRenderer.setInnerText(org.sgo.rootest.client.managed.ui.IssueProxyRenderer.instance().render(proxy));
    }
}
