// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sgo.rootest.domain;

import java.lang.String;

privileged aspect Issue_Roo_ToString {
    
    public String Issue.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("RaisedDate: ").append(getRaisedDate() == null ? "null" : getRaisedDate().getTime()).append(", ");
        sb.append("Summary: ").append(getSummary());
        return sb.toString();
    }
    
}
