// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sgo.rootest.domain;

import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Version;
import org.sgo.rootest.domain.Issue;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Issue_Roo_Entity {
    
    declare @type: Issue: @Entity;
    
    @PersistenceContext
    transient EntityManager Issue.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Issue.id;
    
    @Version
    @Column(name = "version")
    private Integer Issue.version;
    
    public Long Issue.getId() {
        return this.id;
    }
    
    public void Issue.setId(Long id) {
        this.id = id;
    }
    
    public Integer Issue.getVersion() {
        return this.version;
    }
    
    public void Issue.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void Issue.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Issue.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Issue attached = Issue.findIssue(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Issue.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Issue.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Issue Issue.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Issue merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Issue.entityManager() {
        EntityManager em = new Issue().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Issue.countIssues() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Issue o", Long.class).getSingleResult();
    }
    
    public static List<Issue> Issue.findAllIssues() {
        return entityManager().createQuery("SELECT o FROM Issue o", Issue.class).getResultList();
    }
    
    public static Issue Issue.findIssue(Long id) {
        if (id == null) return null;
        return entityManager().find(Issue.class, id);
    }
    
    public static List<Issue> Issue.findIssueEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Issue o", Issue.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
