// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sgo.rootest.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Issue_Roo_Configurable {
    
    declare @type: Issue: @Configurable;
    
}
